domain: ''
port: 8000
views: './app/views'
models: './app/models'
logs: './logs'
public: './public'
resource: './resource'
forgetOversecond: 7200
accessTokenLifetime: 7200
db:
    host: 'localhost'
    name: 'authbox'
    username: 'root'
    password: '123456'
